author: "Alex Flückiger"
name: "Alex Flückiger"
theme: jekyll-theme-cayman

gems:
  - jekyll-target-blank
  
plugins:
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
